MAX=50
def printString(n):
    string=[""]*MAX
    i=0
    while(n>0):
        rem=n%26
        if(rem==0):
            string[i]='Z'
            i+=1
            n=(n//26)-1
        else:
            string[i]=chr((rem-1)+ord('A'))
            i+=1
            n=n//26
    string[i]=''
    string=string[::-1]
    print("".join(string))
n=int(input())
printString(n)